name: uni_v3
rollback_on_reorg: true
unordered_multichain_mode: true
preload_handlers: true
contracts:
  - name: UniswapV3Pool
    handler: src/EventHandlers.ts
    events:
      - event: Initialize(uint160 sqrtPriceX96, int24 tick)
      - event: Collect(address indexed owner, address recipient, int24 indexed tickLower, int24 indexed tickUpper, uint128 amount0, uint128 amount1)
        field_selection:
          transaction_fields:
            - hash
            - gasPrice
      - event: Burn(address indexed owner, int24 indexed tickLower, int24 indexed tickUpper, uint128 amount, uint256 amount0, uint256 amount1)
        field_selection:
          transaction_fields:
            - hash
            - gasPrice
            - from
      - event: Mint(address sender, address indexed owner, int24 indexed tickLower, int24 indexed tickUpper, uint128 amount, uint256 amount0, uint256 amount1)
        field_selection:
          transaction_fields:
            - hash
            - gasPrice
            - from
      - event: Swap(address indexed sender, address indexed recipient, int256 amount0, int256 amount1, uint160 sqrtPriceX96, uint128 liquidity, int24 tick)
        field_selection:
          transaction_fields:
            - hash
            - gasPrice
            - from
networks:
  - id: 8453
    start_block: 0
    contracts:
      - name: UniswapV3Pool
        address:
          - "0x16905890A1D02b6F824387419319Bf4188B961b0"
